"""Test programs generated by a compiler for the Tiger language implemented for CS350.
"""
from .utils import execute_program_helper

from hera.main import main


def helper_stdlib(f, *args):
    preamble = """\
#include <Tiger-stdlib-stack-data.hera>

CBON()
MOVE(R12, SP)
INC(SP, {})
    """
    preamble = preamble.format(len(args) + 3)

    load_args = ""
    for i, arg in enumerate(args):
        load_args += "SET(R1, {})\nSTORE(R1, {}, R12)\n".format(arg, i + 3)

    epilogue = """\
CALL(R12, mod)
LOAD(R1, 3, R12)
DEC(SP, 5)
HALT()

#include <Tiger-stdlib-stack.hera>
    """
    epilogue = epilogue.format(f)

    return preamble + load_args + epilogue


def test_div_and_print(capsys):
    main(["test/assets/cs350/div_and_print.hera"])

    captured = capsys.readouterr()
    assert captured.out == "5"


def test_merge_sort(capsys):
    main(["test/assets/cs350/merge_sort.hera"])

    captured = capsys.readouterr()
    assert captured.out == "42"


def test_lexical_scope_deep(capsys):
    main(["test/assets/cs350/lexical_scope_deep.hera"])

    captured = capsys.readouterr()
    assert captured.out == "42"


def test_stdlib_mod(capsys):
    vm = execute_program_helper(helper_stdlib("mod", 10, 3))

    assert vm.registers[1] == 1
